### ISSUE TITLE
Part 4 작물 잎 사진으로 질병 분류하기 데이터셋 문의

### ISSUE THREAD

**Issue by snoop2head** [bjpublic/DeepLearningProject#2]
해당 프로젝트에 사용되는 데이터셋이 무엇인지 여쭤보고 싶습니다.
그대로 재현을 하고 싶은데, 데이터셋에 대한 얘기가 책에도 깃헙에도 없어서요.

만약 캐글 등 여러 군데에 있는 데이터들을 한 곳에 모은 것이라면, 각각 어디에서 가져왔는지 혹시 알려주실 수 있을까요? 

감사합니다.

**Comment by snoop2head** [comment]
혹시 [Plant Village 데이터셋](https://www.kaggle.com/abdallahalidev/plantvillage-dataset)을 사용하신 걸까요?

**Comment by snoop2head** [comment]
@Annie-Yeeun-Jang @bjpublic  
혹시 [Plant Village 데이터셋](https://www.kaggle.com/abdallahalidev/plantvillage-dataset)을 사용하신 걸까요?

**Comment by Annie-Yeeun-Jang** [comment]
안녕하세요, Part 4 저자입니다.
사용한 데이터의 원본은 https://data.mendeley.com/datasets/tywbtsjrjv/1 에서 다운받으실 수 있습니다.
작물 잎 사진을 통해 해당 작물이 질병을 가지고 있는지의 여부를 판단하는 것이 프로젝트의 목표이기에 원본 데이터에서 한 종류의 작물에 대해 ‘질병’에 해당하는 클래스가 존재하지 않고 ‘건강한’에 해당하는 클래스만 존재하는 경우는 제외하였습니다.
답변이 도움 되셨기를 바랍니다. 감사합니다.

**Comment by snoop2head** [comment]
@Annie-Yeeun-Jang 답변 감사드립니다!
